### ISSUE TITLE
typo in config section of references.md

### ISSUE THREAD

**Issue by amberrignell** [oliverjam/learn-websites#1]
module.exports = (eleventyConfig) => {
  eleventyConfig.addPlugin(syntaxHighlight);
  return {
    dir: {
      input: "src",
    },
  }, <-- expected ; instead of ,
}

**Comment by oliverjam** [comment]
Thank you!

**Comment by oliverjam** [comment]
Fixed in 958eef5fbdb3992ae7e1d27acbaee0d8a2a66634
